language: node_js
node_js:
  - '6'
  - '6.1'
  - '5.11'
before_script:
  - npm install -g gulp
script:
  - gulp travis
  # - npm run-script deploy
  - chmod +x ./deploy-ghpages.sh

env:
  global:
  - ENCRYPTION_LABEL: ac8eb6ebc312
  - COMMIT_AUTHOR_EMAIL: kathirr007@gmail.com
  - GH_REF: https://github.com/kathirr007/HTML-Email-Rendering-issues-and-Solutions.git
  - secure: p/9vd6zqlsr24XZVw/Pbqb3EfP5+YJVEd/Db6tW6mD6ALb/aYPK8T2lyvsc93EevDRattjh4rvca0RVQ7GFARqCbKJsXqnX5xjq7KKSCPMjrXiTDU14VcNz0pNjXXEEa3Y9QfnnW1XsyAL9u/8Hog8+3cDpIkS9/bZge9EQf6BGrmXDkGgHETMPCjTCkkI4G8sWPI0ZQAXdv9jo9m79ETzitucFwuQesh7ERXedzGkZgp1N8rghSLaTobMGxil4r2d3IMUZGU/0HpCCh5mHeVYPT89GmNVMWU0TRutXAJUV7v0VMq+lB+GaGcUBNX38Qh+T0XpB16We5QkonIZbbtF03TirS4wpBdHDREpXMwmSCZsgkF5a3bzOcna+tLaKR1F9s50406NhiGujBNOjk3VBC4O4U4VXnsZxcaHyeV6jgWVxDmfQb/0QIHvShTuQBUTFZ4S7G0713SevN1KeMjiZhrahz9KEucXRMhEbvvzWIL8QKeQiHeXvHqF+Zu1NUowLoROjgRuZx8Rt6m0AcB20PRX5cH/Shynl6LbNzPRW9tHmp7ywjORBG1v1f/uDMhrEn3bXqINfWeBgCu2OB1P15OsmaSq/YMvtCRSGpZJCaEZRJtJFnhIvtmcSpwGel3p3FR72h5Qf565+OGEUbQQ+dEw/x7NVypSBw6iGkYn0=