language: node_js
node_js:
  - '6'
  - '6.1'
  - '5.11'
before_script:
  - npm install -g gulp
  
before_install:  
  - chmod 755 ./deploy-ghpages.sh
script:
  - gulp travis
  - chmod +x ./deploy.sh


after_success:
  - ./deploy-ghpages.sh

env:
  global:
  - secure: a4EYN/itqJ33pIWz7SNMuGUmFAK3s3Yd7k5KnX/hvp7NDat0VB4DBK39+Yjh4QRydSm5kr5KHSLFUHwqOB+AvWjddJJcYBbAkC9xcckI6kIW1UblVZxkttk/iVWliXBDke0hLf6O8oUEbAYWYuYRwzTqxOWFq3E72HizDsmGAtkPlBHNW0jBZKKa7aoW0MPWVeJFbgQKfAXD+mAm2JK6nn2fGVC3GbyVaZgGcidpfGuE+A5qpmg8fvYfmt6Qk0FMMQTu0WUTDQSFlkLK444xKii8G0BdZWHsKo+2Kx0O32SpvJkg7FdozrvHo3BlCkeUYAEQ+SEWWBnrsUn7l1IHYRizwKJcTYR2ER1U9cw8RCCWEabAwXc1lokgQtE9wz8wkuom1N/z4JkCxRndwmY9KFImT7sSKGT8k9wbQNzrR6eEJMzPzGN7NHyBjBlsxBoT1eb3lqMdMBv07XOwT204ehpETUsvbHxrgmiTZ7796FGbG7Gs4ozDXFZSX96AFT/6uXfJA8IMSUfRxPxVNg+MVfYOmYM8DB+stse3MOGzR2nn4nZlwA51ibA9LLJjjtNrX0FQQx5r84TlK/3ROlX2E+jz21ZHW9FI/twoNAAqfDFSx63Wudnza0tV/pu/yfxb939JPPXpyjao/QkSYOzr9ILcFaztp3NHaqnQCIBZDlk=
