language: node_js
node_js:
- '6'
- '6.1'
- '5.11'
env:
  global:
  - GH_TOKEN: da77829939fd462a16a746d61e5f8309015cf4da
  - GH_REF: github.com/kathirr007/HTML-Email-Rendering-issues-and-Solutions.git
  - SSH_KEY: id_rsa
  - GIT_NAME: HTML-Email-Rendering-issues-and-Solutions
  - GIT_EMAIL: kathirr007@gmail.com
  - SOURCE_DIR: builds
  - DEPLOY_BRANCH: master
  - secure: mosBCdc5Bx94yNrAM2quMWiLLTTjIQ5J2bEvoaByu8M7nf7y/OC6Zaz8ZAjJLLY6ZDNqq3bOwb3bCvvZlt00Rt4p/LdO0srHf+ycXC9mx9Z3nFW1dxfCymok1mdpJTEZLj29AtsmCgq9W2LR/Vfkhn1H67olI//zIdxDiGmfET+CW8fYDuL8d1p0J7kZ/ZQB2UxV16FSULm5KWFNgthCozMaDKY4bouWy207EF5Ob5PXhYoODCiwO3QWk+T+Zr0B9iS8RjhSCu0X1JSy9iqYom9lu+8/itGpUQZCY+C8Uq+KgtCP9lyThbPvfmZiAXSYDhl78vikdTCx+fhO5viWtFxOCKEICUR/DZq1Yq/lDlTvFLMOFeL3PgNpAczoqEbR7zgV8Dk5U/EM4HvJ5g7RUs3NREhekhmdPTWDLJD2Q5w/QYRFsGtMoKfjf0KzlNOeH4aSPRMvYAnK0m6tmmaFAbADrcsNRyYzmlMAs88fJYhgHIh6vcL7voPcwplefRFje8kmEVK5uLDTF2QHj46uJWvnSXAx5pi3q1tSPIgjy26FPwsxO59uC0EVzuIwH9VEhLfCV/rrMYPFz4eob6j+5lSfQY0CzUNGCIsDSN3CAuKoJoVwgwWKn9GycZRu1VCTKuPUc5QSjwsQNY5MRl+0xCbPLCLeXsK9bof0iY/f2y8=
branches:
  except:
  - gh-pages
before_script:
- npm install -g gulp
before_install:
- openssl aes-256-cbc -K $encrypted_ac8eb6ebc312_key -iv $encrypted_ac8eb6ebc312_iv
  -in id_rsa.enc -out id_rsa -d
- chmod 755 ./deploy-ghpages.sh
script:
- gulp travis
- chmod +x ./deploy-ghpages.sh
- chmod +x ./deploy.sh
- npm run-script deploy
after_success:
- "./deploy-ghpages.sh"
- "./deploy.sh"
- npm run gh-pages-travis
