language: node_js
node_js:
- '6'
- '6.1'
- '5.11'
env:
  global:
  - GH_TOKEN: da77829939fd462a16a746d61e5f8309015cf4da
  - GH_REF: github.com/kathirr007/HTML-Email-Rendering-issues-and-Solutions
  - SSH_KEY: id_rsa
  - GIT_NAME: HTML-Email-Rendering-issues-and-Solutions
  - GIT_EMAIL: kathirr007@gmail.com
  - SOURCE_DIR: builds
  - DEPLOY_BRANCH: master
  - secure: huY1BOHuLA3hCBofISdIclKLeG7RYH/vTxmP2xd2DW7szsExlLDSJnj5obGlP0s9jmOryrkdPfR3JCFoJs0TaKZGOFwfccClhgfLBJWHvmtRM0wajvgfpQRgspOkkKS+wZitO8PcAD2H31IFRhpAy4AeM49zEfLyVdUMxJ5dfZ1hISg5fZESIx+bPr6njAG/SAw9m4Kr9E50mcC4Rj6X0G60ekUvct2X0JViISXK5z/oC/TVWY78wS4IuVV0iItQopWsvIb2AxtobEFA7o65itnFMrbVWX4lguzi2zOZB91gsrE+O5H97xpbxLx/A0teMTGrrnptZ+jUC5CLpWg9JuaV8Gl+Gk1n5i1Fff5PYn/8OglkRxDIwB7To8qwMYhRHGmSedcLHRigmvcTZjpJLhsp3lqvsbR1afBITt243t2k2ziCIdFEazVGAAVVBSeTpOk6T/mM+UrYALts6sZg+5f5QibGrQaQbzDs+jDw1D1IfQNzXv5lAvuGJZihdVgsWUIUdcNqpJo11o6osZ3T484wjGrUUyeJRBs5oEDx0qHBjpXnKcRTHRR8FQf7/ulzpQvGLJ1jN3dMEJLeD4dH1WK2Nr76uUSazThkoUofrYCIH1f0UB3bm1Q17pFuIWN+Ko180COeuWN7whEVw73Od9mN19OrbsOIxBD2JTB5OXA=
branches:
  only:
    - master
  except:
  - gh-pages
before_install:
- chmod 755 ./deploy-ghpages.sh
before_script:
- git config --global user.name 'Travis-CI'
- git config --global user.email 'travis@travis-ci.org'
- git config --global user.email publish@travis.github && git config --global user.name "Travis"
- sed -i'' "s~git@github.com:kathirr007/HTML-Email-Rendering-issues-and-Solutions.git~https://${GH_TOKEN}:x-oauth-basic@github.com/kathirr007/HTML-Email-Rendering-issues-and-Solutions.git~" _config.yml

before_deploy: git config --global user.email publish@travis.github && git config --global user.name "Travis"
deploy:
  - edge: true
    skip_cleanup: true
    provider: script
    script: gulp deploy
    on:
      branch: master

install:
  # - npm install -g gulp
  - npm install
script:
- gulp travis
- chmod +x ./deploy-ghpages.sh
- chmod +x ./deploy.sh
# - npm run-script deploy
after_success:
- gulp deploy
# - "./deploy.sh"
# - npm run gh-pages-travis
