language: node_js
node_js:
- '6'
- '6.1'
- '5.11'
env:
  global:
   - secure: E6WQUgc5a0Wb6FBre6+fl0kNDHys0+btG5eXVpMOHFKYHmI0Pasw8Ja02ZLuZEM149jwrkyDOerLzhA+dX9rd+arDU3aAUtxEAnCfwlD7fRNN3ykALEzoyaByMP8o+NA7kaJSd37QfTKNAm7ggyYBtAIB92eZpRjPFZr1W4hi9E45Jbv4FqI/vww8TnI9JhmwRtPEk1IjBXpZM5SE1vKTXY/qMS9TbJa88wGglxwCWit0xMjgTzgjI5xKBZulE/36ET+QFQqMoOkkTz29hVU94mMsLXgO7UqsjmiL3gVizi/3kfwRrStm0BryuXBThFL8+LYiYpOlajQ9Dm0gH7jQOG9FQRHFpasG/ymHVTe9tz+ZhV7HFlnTbXcF826l4rJ+x9mhcBWPpfpX0cfwo4vRTzckL0ypCh+jKJ/VSV2ZbHXjHZAvZy+ElTMhETF25DVcooHre6xaB6WFMJEbrP6f775rG8TVCC6IlDBpP4F1+MZ3iTLL/b4OQOZERiyZ5Kkw/as80VgGOPBwHWqkrAKcL6UxT3wz4TdojpO7KdUFE8ROu4QydR8h8FmUzkIPmJ5EjUvpVBIynIhW0tyuxTV3BSJtCUyKp3+oF4xsX+gLh/danfmXuWMp8Jao7IhbtQVpQyWoK5FbEYyRYV9Fy2oJ83ylAHCQMjBOyudZXmOYP8=
branches:
  only:
  - master
  except:
  - gh-pages
before_install:
- chmod 755 ./deploy-ghpages.sh
before_script:
- git config --global user.email "$COMMIT_AUTHOR_EMAIL" && git config --global user.name "Travis CI"
# - git config --global user.email "travis@travis-ci.org"
# - git config --global user.name "Travis CI"

before_deploy:
# - git config --global user.email "kathirr007@gmail.com" 
# - git config --global user.name "kathirr007"
- git config --global user.email "$COMMIT_AUTHOR_EMAIL"
- git config --global user.name "Travis CI"
deploy:
  provider: releases
  api_key: da77829939fd462a16a746d61e5f8309015cf4da
  skip_cleanup: true
  on:
    tags: true
      
install:
- npm install
script:
- gulp travis
- chmod +x ./deploy-ghpages.sh
- chmod +x ./deploy.sh
after_success:
# - gulp deploy
# - "./deploy.sh"
- "./deploy-ghpages.sh"
