language: node_js
node_js:
- '6'
- '6.1'
- '5.11'
env:
  global:
  - secure: E6WQUgc5a0Wb6FBre6+fl0kNDHys0+btG5eXVpMOHFKYHmI0Pasw8Ja02ZLuZEM149jwrkyDOerLzhA+dX9rd+arDU3aAUtxEAnCfwlD7fRNN3ykALEzoyaByMP8o+NA7kaJSd37QfTKNAm7ggyYBtAIB92eZpRjPFZr1W4hi9E45Jbv4FqI/vww8TnI9JhmwRtPEk1IjBXpZM5SE1vKTXY/qMS9TbJa88wGglxwCWit0xMjgTzgjI5xKBZulE/36ET+QFQqMoOkkTz29hVU94mMsLXgO7UqsjmiL3gVizi/3kfwRrStm0BryuXBThFL8+LYiYpOlajQ9Dm0gH7jQOG9FQRHFpasG/ymHVTe9tz+ZhV7HFlnTbXcF826l4rJ+x9mhcBWPpfpX0cfwo4vRTzckL0ypCh+jKJ/VSV2ZbHXjHZAvZy+ElTMhETF25DVcooHre6xaB6WFMJEbrP6f775rG8TVCC6IlDBpP4F1+MZ3iTLL/b4OQOZERiyZ5Kkw/as80VgGOPBwHWqkrAKcL6UxT3wz4TdojpO7KdUFE8ROu4QydR8h8FmUzkIPmJ5EjUvpVBIynIhW0tyuxTV3BSJtCUyKp3+oF4xsX+gLh/danfmXuWMp8Jao7IhbtQVpQyWoK5FbEYyRYV9Fy2oJ83ylAHCQMjBOyudZXmOYP8=
  - secure: DzU5qAqHTWIe4nupZj57/NYmM6hlh9I7aP74dIDLMiqVDz+Lv4zbXpfus1Bd6iuE5cfDoJiRqis93SYuFuN1mlpH///edmGJqlV/OCoL5I03As+fkW101n/e2ZtnFFe8l+o+sr6j9yTrQhSvgyJwOliZDeE+eVEZrZCYbEB3V2GN0+9b9iZ/nbA8MhtbVhtYvzHCeS2s9V3MiWzJrO5XVUrQTyUsPGiZD5RDJ/0BBKUiSnDuMs0lnmm+883NYl2xaeWN3YQ/cOxxyrQKvMuA1IJQ8i483XE68KeeyhcthQt1va2jDmhb/2uNhQfnw/snetZXSqOm0C9UnJ4yEAdLSgfChDtPXmyRqiIIvUVTtGFRD8OODuv4eJI8O/ipo2VZRXkM9LG/WXnbqD9klPrX+hGetVZgwQ1k4XLnj1jlFiN2SDYh1Xv42vZZI0hx74dPqrVF8Q6a3jBapWoe7VMTdXSKswOpBKkCsvr31cg0sCiQMrdPYDwnHDjCE74QQbxRRjP6HM6Ai8/7QbxUoX9gARfMTB+15w96zUynZM8ilBDwJKc7PVEMNFGDOI0vNUuup2VtMkCmO+XY1fPNo7EnOfc+ChHaRDU4PJZ0qsFzZlQnMlbrE8SGarZoU3xX4OG4A3KajUCeYMba6oNVbn0XRkBAn0uJY/1uoufGUmAL4Vg=
  - secure: GNBWTeLq5go4+AXVHa5L5G5XKFNrhLAAymopF/RzGbMLGXseTEpFrw51Y+Xr9SdHXZN1xA8pr5evCIwWL73UuIuUbvpIikO/DVSs3WtNN5IpXG8GLPFLCT8ZP/yxUpJ+O+4RgMEcRI6SekdhI2HvWhPSY4m/8nVO4JTGRzISPEx3hds9z/OKQ10aplt58rD531zCRZA6lTlNgld0+Ok/7/n4xadbyFf4AG5lrkinCiUzVTlvmhV2++wmUSFd1iA9zCPo/56b8iqDK3Ey/iaFupYJfMfRWd/T/LSa1HU64rbQlt1mMgRcNg3Zmn6/TYm3J22Zx9SP1Zzn8Vy6C4y0y+TnjRy/lNI1x7d47BG9NHwvcef3jca7rIvcb5sVPLo+xomKSpBNTmrrw4yR1peYT8ERZyKHr/QaSiEVTRUaB/OECWU+9L5T2+cfylPVLsBhIdDMLaRvZg/jexeIX1okslIdNpivZOFzKPcpDZ0MC1rV/v82+JmDGEihpq1ro3zXUz3Vzqcx71kgzqQuf6JpltUGoYlSPUGfKD/4pBXucvXzAq4mzMV6RWe4+NNMYFlYc7IBZs4TC09l5hWXnBcYtzXY9VmUQeUQz/OxR0PtUhSZAB4K3P12cFpsBMxjKfbYrOyuUMlk76r0kyEenziQIu/st7aLY0/5QeAMgV+njbs=
branches:
  only:
  - master
  except:
  - gh-pages
before_install:
- chmod 755 ./deploy-ghpages.sh
before_script:
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis"
before_deploy:
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis"
deploy:
- provider: releases
  api_key: da77829939fd462a16a746d61e5f8309015cf4da
  skip_cleanup: true
  on:
    tags: true
- edge: true
  skip_cleanup: true
  provider: script
  script: gulp deploy
  on:
    branch: master
install:
- npm install
script:
- gulp travis
- chmod +x ./deploy-ghpages.sh
- chmod +x ./deploy.sh
after_success:
- "./deploy-ghpages.sh"
